config/routes.rb
Rails.application.routes.draw do
  get 'experiments/page1'

  get 'experiments/page2'

  get 'experiments/page3'

  get 'page1/page2'

  get 'page1/page3'

  get 'pages/batman'

  get 'pages/superman'

  get 'pages/batman-vs-superman'

  post 'pages/save_data'

  root 'pages#batman_vs_superman'

end

app/models/vote.rb
class Vote < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController

  layout "bootstrap"
  
  def page1
      
  end

  def page2
  end

  def page3
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def batman
  
  end

  def superman

  end

  def batman_vs_superman

  end

  def save_data
    if params[:email].present? 
    Vote.new(
              hero: params[:hero],
              email: params[:email]
      ).save

      redirect_to root_path, notice:"Voto registrado"
    else
      flash[:alert] = "Ingrese su E-Mail"
      render :batman_vs_superman
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/experiments/page1.html.erb
<h1>Lorem Ipsum 1</h1>

Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años, sino que tambien ingresó como texto de relleno en documentos electrónicos, quedando esencialmente igual al original. Fue popularizado en los 60s con la creación de las hojas "Letraset", las cuales contenian pasajes de Lorem Ipsum, y más recientemente con software de autoedición, como por ejemplo Aldus PageMaker, el cual incluye versiones de Lorem Ipsum.

app/views/experiments/page2.html.erb
<h1>Lorem Ipsum 2</h1>

Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años, sino que tambien ingresó como texto de relleno en documentos electrónicos, quedando esencialmente igual al original. Fue popularizado en los 60s con la creación de las hojas "Letraset", las cuales contenian pasajes de Lorem Ipsum, y más recientemente con software de autoedición, como por ejemplo Aldus PageMaker, el cual incluye versiones de Lorem Ipsum.

app/views/experiments/page3.html.erb
<h1>Lorem Ipsum 3</h1>

Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años, sino que tambien ingresó como texto de relleno en documentos electrónicos, quedando esencialmente igual al original. Fue popularizado en los 60s con la creación de las hojas "Letraset", las cuales contenian pasajes de Lorem Ipsum, y más recientemente con software de autoedición, como por ejemplo Aldus PageMaker, el cual incluye versiones de Lorem Ipsum.

app/views/layouts/_navbar.html.erb
<div class="container">
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Prueba de Rails</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if controller.action_name == 'page1' %>"><a href="/experiments/page1">Página 1 <span class="sr-only">(current)</span></a></li>
        <li class="<%= 'active' if controller.action_name == 'page2' %>"><a href="/experiments/page2">Página 2</a></li>
        <li class="<%= 'active' if controller.action_name == 'page3' %>"><a href="/experiments/page3">Página 3</a></li>
        
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Superheroes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag controller.action_name, 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/bootstrap.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AssetPath</title>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">


	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

	<%= csrf_meta_tags %>
	
	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</head>
<body class='<%= "#{controller_name} #{action_name}" %>'>
<%= render 'layouts/navbar' %>
<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/pages/batman.html.erb
<h1>I'm Batman!</h1>

app/views/pages/batman_vs_superman.html.erb
<style>
img {
    width: 40%;
}

</style>

<% if notice %>
<div class="alert alert-success" role="alert">
<strong>Excelente!</strong> <%= notice %>
</div>
<% elsif alert %>
<div class="alert alert-warning" role="alert">
<strong>Warning!</strong> <%= alert %>
</div>
<% end %>

<div>
<%= link_to image_tag("batman2.jpg"), pages_batman_path %>
<%= form_tag pages_save_data_path, method: "post" do %>
	<div class="form-group">
		<%= label_tag :email, 'Ingrese su E-Mail para registrar su voto' %>
		<%= text_field_tag :email, params[:email] , class: "form-control"%>
		<%= hidden_field_tag 'hero', 'superman', class: "form-control" %>
	</div>
	<div class="form-group">
		<%= submit_tag "Enviar", class:"btn btn-success" %>
	</div>
<% end %>
</div>
<div>
<%= link_to image_tag("superman2.jpg"), pages_superman_path %>
<%= form_tag pages_save_data_path, method: "post" do %>
	<div class="form-group">
		<%= label_tag :email, 'Ingrese su E-Mail para registrar su voto' %>
		<%= text_field_tag :email, params[:email] , class: "form-control"%>
		<%= hidden_field_tag 'hero', 'superman' , class: "form-control" %>
	</div>
	<div class="form-group">
		<%= submit_tag "Enviar", class:"btn btn-success" %>
	</div>
<% end %>
</div>

app/views/pages/superman.html.erb
<h1>This looks like a job for Superman</h1>